<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[- execution velocity -> normal]]>
    </line>
    <line>
      <![CDATA[- start system driver process ...]]>
    </line>
    <line>
      <![CDATA[- property 'text' with actual value 'Linkedin' is not equals to 'Linkedi' after 12203 ms]]>
    </line>
  </reporter-output>
  <suite started-at="2025-10-19T20:09:32 CEST" name="suite" finished-at="2025-10-19T20:09:59 CEST" duration-ms="27229">
    <groups>
    </groups>
    <test started-at="2025-10-19T20:09:32 CEST" name="Scenario_1" finished-at="2025-10-19T20:09:59 CEST" duration-ms="27229">
      <class name="Scenario_1">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:Scenario_1@35dab4eb]" started-at="2025-10-19T20:09:31 CEST" name="beforeSuite" test-instance-name="Scenario_1" finished-at="2025-10-19T20:09:32 CEST" duration-ms="41" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeClass(org.testng.ITestContext)[pri:0, instance:Scenario_1@35dab4eb]" started-at="2025-10-19T20:09:32 CEST" name="beforeClass" test-instance-name="Scenario_1" finished-at="2025-10-19T20:09:32 CEST" duration-ms="15" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1716e8c5]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[- execution velocity -> normal]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="TcScenario_1()[pri:0, instance:Scenario_1@35dab4eb]" started-at="2025-10-19T20:09:32 CEST" name="TcScenario_1" test-instance-name="Scenario_1" finished-at="2025-10-19T20:09:56 CEST" duration-ms="24916" status="FAIL">
          <exception class="com.ats.tools.logger.levels.AtsFailError">
            <message>
              <![CDATA[ActionAssertProperty (Scenario_1:2) -> {"app":"msedge","errorCode":-6,"errorMessage":"property 'text' with actual value 'Linkedin' is not equals to 'Linkedi' after 12203 ms"}]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.ats.tools.logger.levels.AtsFailError: ActionAssertProperty (Scenario_1:2) -> {"app":"msedge","errorCode":-6,"errorMessage":"property 'text' with actual value 'Linkedin' is not equals to 'Linkedi' after 12203 ms"}
at com.ats.executor.ActionTestScript.actionFinished(ActionTestScript.java:1361)
at com.ats.executor.ActionTestScript.exec(ActionTestScript.java:1300)
at Scenario_1.TcScenario_1(Scenario_1.java:85)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.TestNG.privateMain(TestNG.java:1430)
at org.testng.TestNG.main(TestNG.java:1394)
]]>
            </full-stacktrace>
          </exception> <!-- com.ats.tools.logger.levels.AtsFailError -->
          <reporter-output>
            <line>
              <![CDATA[- start system driver process ...]]>
            </line>
            <line>
              <![CDATA[- property 'text' with actual value 'Linkedin' is not equals to 'Linkedi' after 12203 ms]]>
            </line>
          </reporter-output>
        </test-method> <!-- TcScenario_1 -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:Scenario_1@35dab4eb]" started-at="2025-10-19T20:09:56 CEST" name="cleanup" test-instance-name="Scenario_1" finished-at="2025-10-19T20:09:59 CEST" duration-ms="2268" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "com.ats.recorder.TestSummary.getActions()" because "testSummary[0]" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "com.ats.recorder.TestSummary.getActions()" because "testSummary[0]" is null
at com.ats.tools.report.XmlReport.createReport(XmlReport.java:329)
at com.ats.recorder.VisualRecorder.terminate(VisualRecorder.java:163)
at com.ats.executor.ActionTestScript.setRecorder(ActionTestScript.java:1451)
at com.ats.executor.ActionTestScript.stopRecorder(ActionTestScript.java:1472)
at com.ats.executor.ActionTestScript.cleanup(ActionTestScript.java:673)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:836)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:805)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:781)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.TestNG.privateMain(TestNG.java:1430)
at org.testng.TestNG.main(TestNG.java:1394)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
        <test-method is-config="true" signature="afterClass(org.testng.ITestContext)[pri:0, instance:Scenario_1@35dab4eb]" started-at="2025-10-19T20:09:59 CEST" name="afterClass" test-instance-name="Scenario_1" finished-at="2025-10-19T20:09:59 CEST" duration-ms="7" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1716e8c5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:Scenario_1@35dab4eb]" started-at="2025-10-19T20:09:59 CEST" name="afterSuite" test-instance-name="Scenario_1" finished-at="2025-10-19T20:09:59 CEST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- Scenario_1 -->
    </test> <!-- Scenario_1 -->
  </suite> <!-- suite -->
</testng-results>
